version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - npm ci
  build:
    commands:
        - npm run build -- --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/bookstore'
